app:
  kafka:
    topic: resultado-votacao

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-votacao
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*" # expõe todos os endpoints
    shutdown:
      enabled: true
    health:
      show-details: always
    httptrace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true
