global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'springboot-kafka-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-api:8080'] # API rodando na máquina local
