app:
  kafka:
    topic: resultado-votacao

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: grupo-votacao
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/votacao}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      
  jpa:
    hibernate:
      ddl-auto: update  # cria/atualiza as tabelas automaticamente
    show-sql: true      # opcional, para ver as queries geradas

  zipkin:
    base-url: http://zipkin:9411 
  sleuth:
    sampler:
      probability: 1.0  # envia todos os spans


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-check-sums: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,httptrace,shutdown
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080
  address: 0.0.0.0
